    static let kilimanjaro = Mountain(
        name: "Mount Kilimanjaro",
        height: 5895,
        location: "Tanzania, Africa",
        difficulty: .intermediate,
        description: "The highest peak in Africa and the highest free-standing mountain in the world. A non-technical climb but requires excellent fitness and acclimatization.",
        imageName: "kilimanjaro",
        isPaywalled: False,
        camps: [
            Camp(name: "Base Camp", altitude: 1828, stepsRequired: 0, elevationRequired: 0, description: "Starting point of your expedition", unlockedMessage: "Welcome to the mountain!", isBaseCamp: True, isSummit: False),
            Camp(name: "Camp 1 - Mandara", altitude: 2700, stepsRequired: 21800, elevationRequired: 872, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Camp 1 - Mandara!", isBaseCamp: False, isSummit: False),
            Camp(name: "Camp 2 - Horombo", altitude: 3720, stepsRequired: 47300, elevationRequired: 1892, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Camp 2 - Horombo!", isBaseCamp: False, isSummit: False),
            Camp(name: "Camp 3 - Kibo", altitude: 4700, stepsRequired: 71800, elevationRequired: 2872, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Camp 3 - Kibo!", isBaseCamp: False, isSummit: False),
            Camp(name: "Uhuru Peak", altitude: 5895, stepsRequired: 101675, elevationRequired: 4067, description: "The summit of the mountain", unlockedMessage: "Congratulations! You've reached the summit!", isBaseCamp: False, isSummit: True),
        ],
        baseSteps: 101675,
        baseElevation: 4067,
        baseElevationStart: 1828,
        totalElevationGain: 4067,
        difficultyMultiplier: 8.0,
        estimatedDays: 7,
        climbingSeason: .spring,
        weatherPatterns: [.clear, .cloudy, .windy],
        hazards: [.altitudeSickness, .frostbite],
        equipmentRequirements: [.helmet, .rope],
        historicalData: .kilimanjaro
    )

    static let everest = Mountain(
        name: "Mount Everest",
        height: 8848,
        location: "Nepal/Tibet, Asia",
        difficulty: .extreme,
        description: "The world's highest peak and ultimate mountaineering challenge. Requires extreme fitness, technical skills, and months of preparation.",
        imageName: "everest",
        isPaywalled: True,
        camps: [
            Camp(name: "Base Camp", altitude: 5364, stepsRequired: 0, elevationRequired: 0, description: "Starting point of your expedition", unlockedMessage: "Welcome to the mountain!", isBaseCamp: True, isSummit: False),
            Camp(name: "Camp 1", altitude: 6065, stepsRequired: 70100, elevationRequired: 701, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Camp 1!", isBaseCamp: False, isSummit: False),
            Camp(name: "Camp 2", altitude: 6400, stepsRequired: 103600, elevationRequired: 1036, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Camp 2!", isBaseCamp: False, isSummit: False),
            Camp(name: "Camp 3", altitude: 7200, stepsRequired: 183600, elevationRequired: 1836, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Camp 3!", isBaseCamp: False, isSummit: False),
            Camp(name: "Camp 4", altitude: 8000, stepsRequired: 263600, elevationRequired: 2636, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Camp 4!", isBaseCamp: False, isSummit: False),
            Camp(name: "Summit", altitude: 8848, stepsRequired: 348400, elevationRequired: 3484, description: "The summit of the mountain", unlockedMessage: "Congratulations! You've reached the summit!", isBaseCamp: False, isSummit: True),
        ],
        baseSteps: 348400,
        baseElevation: 3484,
        baseElevationStart: 5364,
        totalElevationGain: 3484,
        difficultyMultiplier: 25.0,
        estimatedDays: 35,
        climbingSeason: .spring,
        weatherPatterns: [.clear, .cloudy, .windy, .storm, .blizzard],
        hazards: [.altitudeSickness, .avalanches, .crevasses, .frostbite],
        equipmentRequirements: [.iceAxe, .crampons, .helmet, .oxygenBottle, .rope, .gps],
        historicalData: .everest
    )

    static let fuji = Mountain(
        name: "Mount Fuji",
        height: 3776,
        location: "Japan, Asia",
        difficulty: .beginner,
        description: "Japan's most iconic mountain and a sacred symbol. A popular day hike with well-maintained trails.",
        imageName: "fuji",
        isPaywalled: False,
        camps: [
            Camp(name: "Base Camp", altitude: 2305, stepsRequired: 0, elevationRequired: 0, description: "Starting point of your expedition", unlockedMessage: "Welcome to the mountain!", isBaseCamp: True, isSummit: False),
            Camp(name: "Station 5", altitude: 2390, stepsRequired: 1275, elevationRequired: 85, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Station 5!", isBaseCamp: False, isSummit: False),
            Camp(name: "Station 8", altitude: 3100, stepsRequired: 11925, elevationRequired: 795, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Station 8!", isBaseCamp: False, isSummit: False),
            Camp(name: "Summit", altitude: 3776, stepsRequired: 22065, elevationRequired: 1471, description: "The summit of the mountain", unlockedMessage: "Congratulations! You've reached the summit!", isBaseCamp: False, isSummit: True),
        ],
        baseSteps: 22065,
        baseElevation: 1471,
        baseElevationStart: 2305,
        totalElevationGain: 1471,
        difficultyMultiplier: 3.0,
        estimatedDays: 1,
        climbingSeason: .summer,
        weatherPatterns: [.clear, .cloudy],
        hazards: [],
        equipmentRequirements: [],
        historicalData: .fuji
    )

    static let rainier = Mountain(
        name: "Mount Rainier",
        height: 4392,
        location: "Washington, USA",
        difficulty: .advanced,
        description: "The most glaciated peak in the contiguous United States. Requires glacier travel skills and crevasse rescue knowledge.",
        imageName: "rainier",
        isPaywalled: False,
        camps: [
            Camp(name: "Base Camp", altitude: 1500, stepsRequired: 0, elevationRequired: 0, description: "Starting point of your expedition", unlockedMessage: "Welcome to the mountain!", isBaseCamp: True, isSummit: False),
            Camp(name: "Camp Muir", altitude: 3000, stepsRequired: 60000, elevationRequired: 1500, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Camp Muir!", isBaseCamp: False, isSummit: False),
            Camp(name: "Summit", altitude: 4392, stepsRequired: 115680, elevationRequired: 2892, description: "The summit of the mountain", unlockedMessage: "Congratulations! You've reached the summit!", isBaseCamp: False, isSummit: True),
        ],
        baseSteps: 115680,
        baseElevation: 2892,
        baseElevationStart: 1500,
        totalElevationGain: 2892,
        difficultyMultiplier: 12.0,
        estimatedDays: 3,
        climbingSeason: .summer,
        weatherPatterns: [.clear, .cloudy, .windy, .storm],
        hazards: [.crevasses, .avalanches, .altitudeSickness],
        equipmentRequirements: [.iceAxe, .crampons, .helmet, .rope],
        historicalData: .rainier
    )

    static let blanc = Mountain(
        name: "Mont Blanc",
        height: 4808,
        location: "France/Italy, Europe",
        difficulty: .expert,
        description: "The highest peak in the Alps and Western Europe. Requires alpine climbing skills and experience with high altitude.",
        imageName: "blanc",
        isPaywalled: True,
        camps: [
            Camp(name: "Base Camp", altitude: 1000, stepsRequired: 0, elevationRequired: 0, description: "Starting point of your expedition", unlockedMessage: "Welcome to the mountain!", isBaseCamp: True, isSummit: False),
            Camp(name: "Refuge du Goûter", altitude: 3000, stepsRequired: 120000, elevationRequired: 2000, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Refuge du Goûter!", isBaseCamp: False, isSummit: False),
            Camp(name: "Summit", altitude: 4808, stepsRequired: 228480, elevationRequired: 3808, description: "The summit of the mountain", unlockedMessage: "Congratulations! You've reached the summit!", isBaseCamp: False, isSummit: True),
        ],
        baseSteps: 228480,
        baseElevation: 3808,
        baseElevationStart: 1000,
        totalElevationGain: 3808,
        difficultyMultiplier: 15.0,
        estimatedDays: 5,
        climbingSeason: .summer,
        weatherPatterns: [.clear, .cloudy, .windy, .storm],
        hazards: [.altitudeSickness, .avalanches, .rockfall],
        equipmentRequirements: [.iceAxe, .crampons, .helmet, .rope],
        historicalData: .blanc
    )

    static let elcapitan = Mountain(
        name: "El Capitan",
        height: 2121,
        location: "Yosemite, USA",
        difficulty: .expert,
        description: "The legendary granite monolith in Yosemite Valley. Requires advanced rock climbing skills and multi-day commitment.",
        imageName: "elcapitan",
        isPaywalled: True,
        camps: [
            Camp(name: "Base", altitude: 1207, stepsRequired: 0, elevationRequired: 0, description: "Starting point of your expedition", unlockedMessage: "Welcome to the mountain!", isBaseCamp: True, isSummit: False),
            Camp(name: "Pitch 10", altitude: 1400, stepsRequired: 11580, elevationRequired: 193, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Pitch 10!", isBaseCamp: False, isSummit: False),
            Camp(name: "Pitch 20", altitude: 1600, stepsRequired: 23580, elevationRequired: 393, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Pitch 20!", isBaseCamp: False, isSummit: False),
            Camp(name: "Pitch 30", altitude: 1800, stepsRequired: 35580, elevationRequired: 593, description: "Intermediate camp on the mountain", unlockedMessage: "You've reached Pitch 30!", isBaseCamp: False, isSummit: False),
            Camp(name: "Summit", altitude: 2121, stepsRequired: 54840, elevationRequired: 914, description: "The summit of the mountain", unlockedMessage: "Congratulations! You've reached the summit!", isBaseCamp: False, isSummit: True),
        ],
        baseSteps: 54840,
        baseElevation: 914,
        baseElevationStart: 1207,
        totalElevationGain: 914,
        difficultyMultiplier: 15.0,
        estimatedDays: 4,
        climbingSeason: .summer,
        weatherPatterns: [.clear, .cloudy, .windy],
        hazards: [.rockfall],
        equipmentRequirements: [.rope, .helmet],
        historicalData: .elcapitan
    )
